# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YQ_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YQ_form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1817, 758)
        Form.setStyleSheet("background-color: rgb(229, 240, 255);")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(0, 40, 1811, 51))
        self.label_title.setStyleSheet("font: 75 24pt \"微软雅黑\";\n"
"background-color: rgb(229, 240, 255);\n"
"color: rgb(39, 154, 255);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(830, 120, 431, 621))
        self.groupBox_2.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.photo_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.photo_btn.setGeometry(QtCore.QRect(140, 160, 121, 41))
        self.photo_btn.setStyleSheet("border-image: url(:/newPrefix/picture/btn_photo_normal.png);")
        self.photo_btn.setText("")
        self.photo_btn.setObjectName("photo_btn")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(40, 220, 361, 331))
        self.groupBox.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.groupBox.setObjectName("groupBox")
        self.textage = QtWidgets.QTextEdit(self.groupBox)
        self.textage.setGeometry(QtCore.QRect(30, 150, 281, 31))
        self.textage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textage.setObjectName("textage")
        self.label_mask = QtWidgets.QLabel(self.groupBox)
        self.label_mask.setGeometry(QtCore.QRect(10, 30, 161, 31))
        self.label_mask.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_mask.setObjectName("label_mask")
        self.text_mask = QtWidgets.QTextEdit(self.groupBox)
        self.text_mask.setGeometry(QtCore.QRect(30, 70, 281, 31))
        self.text_mask.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_mask.setObjectName("text_mask")
        self.label_age = QtWidgets.QLabel(self.groupBox)
        self.label_age.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.label_age.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_age.setObjectName("label_age")
        self.text_fever = QtWidgets.QTextEdit(self.groupBox)
        self.text_fever.setGeometry(QtCore.QRect(180, 240, 131, 31))
        self.text_fever.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_fever.setObjectName("text_fever")
        self.label_fever = QtWidgets.QLabel(self.groupBox)
        self.label_fever.setGeometry(QtCore.QRect(170, 200, 111, 31))
        self.label_fever.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_fever.setObjectName("label_fever")
        self.label_temp = QtWidgets.QLabel(self.groupBox)
        self.label_temp.setGeometry(QtCore.QRect(10, 200, 111, 31))
        self.label_temp.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_temp.setObjectName("label_temp")
        self.text_temp = QtWidgets.QTextEdit(self.groupBox)
        self.text_temp.setGeometry(QtCore.QRect(10, 240, 151, 31))
        self.text_temp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_temp.setObjectName("text_temp")
        self.photo_yc = QtWidgets.QPushButton(self.groupBox)
        self.photo_yc.setGeometry(QtCore.QRect(210, 20, 101, 41))
        self.photo_yc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(39, 154, 255);\n"
"font: 75 12pt \"微软雅黑\";")
        self.photo_yc.setObjectName("photo_yc")
        self.camera_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.camera_btn.setGeometry(QtCore.QRect(90, 80, 101, 41))
        self.camera_btn.setStyleSheet("border-image: url(:/newPrefix/picture/btn_off.png);")
        self.camera_btn.setText("")
        self.camera_btn.setObjectName("camera_btn")
        self.label_camera_open = QtWidgets.QLabel(self.groupBox_2)
        self.label_camera_open.setGeometry(QtCore.QRect(40, 40, 111, 31))
        self.label_camera_open.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_camera_open.setObjectName("label_camera_open")
        self.label_camera_photo = QtWidgets.QLabel(self.groupBox_2)
        self.label_camera_photo.setGeometry(QtCore.QRect(40, 130, 111, 31))
        self.label_camera_photo.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_camera_photo.setObjectName("label_camera_photo")
        self.photo_btn_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.photo_btn_2.setGeometry(QtCore.QRect(170, 570, 121, 41))
        self.photo_btn_2.setStyleSheet("border-image: url(:/newPrefix/picture/btn_photo_normal.png);\n"
"border-image: url(:/newPrefix/picture/btn_photo_normal1.png);")
        self.photo_btn_2.setText("")
        self.photo_btn_2.setObjectName("photo_btn_2")
        self.label_upload = QtWidgets.QLabel(self.groupBox_2)
        self.label_upload.setGeometry(QtCore.QRect(40, 550, 111, 31))
        self.label_upload.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_upload.setObjectName("label_upload")
        self.label_zhushi = QtWidgets.QLabel(self.groupBox_2)
        self.label_zhushi.setGeometry(QtCore.QRect(50, 510, 341, 31))
        self.label_zhushi.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(255, 0, 0);")
        self.label_zhushi.setObjectName("label_zhushi")
        self.label_info = QtWidgets.QLabel(self.groupBox_2)
        self.label_info.setGeometry(QtCore.QRect(220, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_info.setFont(font)
        self.label_info.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.label_info.setText("")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(80, 640, 731, 101))
        self.groupBox_3.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_zhushi_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_zhushi_3.setGeometry(QtCore.QRect(20, 30, 471, 51))
        self.label_zhushi_3.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(85, 0, 255);")
        self.label_zhushi_3.setWordWrap(True)
        self.label_zhushi_3.setObjectName("label_zhushi_3")
        self.label_zhushi_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_zhushi_2.setGeometry(QtCore.QRect(480, 20, 231, 61))
        self.label_zhushi_2.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(255, 0, 0);")
        self.label_zhushi_2.setWordWrap(True)
        self.label_zhushi_2.setObjectName("label_zhushi_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(80, 130, 731, 511))
        self.groupBox_4.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_show_camera = QtWidgets.QLabel(self.groupBox_4)
        self.label_show_camera.setGeometry(QtCore.QRect(10, 30, 711, 471))
        self.label_show_camera.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_camera.setText("")
        self.label_show_camera.setObjectName("label_show_camera")
        self.photo_sx = QtWidgets.QPushButton(Form)
        self.photo_sx.setGeometry(QtCore.QRect(1520, 680, 131, 41))
        self.photo_sx.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(39, 154, 255);\n"
"font: 75 12pt \"微软雅黑\";")
        self.photo_sx.setObjectName("photo_sx")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(1280, 120, 531, 531))
        self.groupBox_5.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: rgb(39, 154, 255);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_show_photo_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_show_photo_2.setGeometry(QtCore.QRect(20, 30, 491, 481))
        self.label_show_photo_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_photo_2.setText("")
        self.label_show_photo_2.setObjectName("label_show_photo_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "疫情防控"))
        self.groupBox_2.setTitle(_translate("Form", "功能区："))
        self.groupBox.setTitle(_translate("Form", "模型预测："))
        self.label_mask.setText(_translate("Form", "是否匹配戴口罩："))
        self.label_age.setText(_translate("Form", "年龄预测："))
        self.label_fever.setText(_translate("Form", "发烧预测："))
        self.label_temp.setText(_translate("Form", "体温输入："))
        self.photo_yc.setText(_translate("Form", "预测"))
        self.label_camera_open.setText(_translate("Form", "摄像头开关："))
        self.label_camera_photo.setText(_translate("Form", "拍照开关："))
        self.label_upload.setText(_translate("Form", "上报云端："))
        self.label_zhushi.setText(_translate("Form", "（注意：发烧为布尔值1，未发烧为0）"))
        self.groupBox_3.setTitle(_translate("Form", "各年龄段正常体温范围对照表："))
        self.label_zhushi_3.setText(_translate("Form", "0-2岁：36.4-38.0℃           3-10岁：36.1-37.8℃     11-65岁：35.9-37.5℃        >65岁：35.8-37.4℃"))
        self.label_zhushi_2.setText(_translate("Form", "该表用于对发烧的预测，以提高发烧判别的准确性"))
        self.groupBox_4.setTitle(_translate("Form", "视频区："))
        self.photo_sx.setText(_translate("Form", "刷新"))
        self.groupBox_5.setTitle(_translate("Form", "拍照区："))
import YQ_demo_rc
